In [41]:
import pandas as pd
import datetime
import numpy as np

##### Deep learning

##### ANN with Pytorch


##### Feature engineering
Categorial --- Embedding layer
Continous variable

##### pythonic class to create NN  Feed forward



In [2]:
df = pd.read_csv('houseprice.csv')

In [4]:
df.head(5)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [5]:
df.shape

(1460, 81)

In [9]:
df = df[['MSSubClass','MSZoning','LotFrontage', 'Street','LotShape','YearBuilt', '1stFlrSF','2ndFlrSF','SalePrice']]


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 9 columns):
MSSubClass     1460 non-null int64
MSZoning       1460 non-null object
LotFrontage    1201 non-null float64
Street         1460 non-null object
LotShape       1460 non-null object
YearBuilt      1460 non-null int64
1stFlrSF       1460 non-null int64
2ndFlrSF       1460 non-null int64
SalePrice      1460 non-null int64
dtypes: float64(1), int64(5), object(3)
memory usage: 102.7+ KB


In [11]:
for i in df.columns:
    print("Column name {} has {} unique values".format(i,len(df[i].unique())))

Column name MSSubClass has 15 unique values
Column name MSZoning has 5 unique values
Column name LotFrontage has 111 unique values
Column name Street has 2 unique values
Column name LotShape has 4 unique values
Column name YearBuilt has 112 unique values
Column name 1stFlrSF has 753 unique values
Column name 2ndFlrSF has 417 unique values
Column name SalePrice has 663 unique values


In [19]:

yearnow = datetime.datetime.now().year

In [20]:
df['Total Years'] = yearnow - df['YearBuilt']

C:\Users\GPACKIRI\anaconda3\envs\envpytorch\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [24]:
df['Total Years'].head()

0     21
1     48
2     23
3    109
4     24
Name: Total Years, dtype: int64

In [26]:
df.drop('YearBuilt',axis=1,inplace = True)

C:\Users\GPACKIRI\anaconda3\envs\envpytorch\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [32]:
### Creating categorical features

cat_features = ['MSSubClass', 'MSZoning','Street','LotShape']

out_features = ['SalePrice']


In [29]:
# Label encoding
from sklearn.preprocessing import LabelEncoder

lbl_encoders ={}

lbl_encoders['MSSubClass']   =  LabelEncoder()
lbl_encoders['MSSubClass'].fit_transform(df['MSSubClass'])

array([5, 0, 5, ..., 6, 0, 0], dtype=int64)

In [35]:
lbl_encoders

{'MSSubClass': LabelEncoder(),
 'MSZoning': LabelEncoder(),
 'Street': LabelEncoder(),
 'LotShape': LabelEncoder()}

In [36]:
from sklearn.preprocessing import LabelEncoder

lbl_encoders ={}

for feature in cat_features:
    lbl_encoders[feature]   =  LabelEncoder()
    df[feature] = lbl_encoders[feature].fit_transform(df[feature])

C:\Users\GPACKIRI\anaconda3\envs\envpytorch\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


In [38]:
df.head(2)

MSSubClass  MSZoning  LotFrontage  Street  LotShape  1stFlrSF  2ndFlrSF  \
0           5         3         65.0       1         3       856       854   
1           0         3         80.0       1         3      1262         0   

   SalePrice  Total Years  
0     208500           21  
1     181500           48

In [42]:
cat_feature = np.stack([df['MSSubClass'],df['MSZoning'],df['Street'],df['LotShape']],1 )
cat_feature

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]], dtype=int64)

In [45]:
import torch

cat_feature = torch.tensor(cat_feature,dtype=torch.int64)

In [ ]:
#### Treating continous values

In [56]:
cont_features = []

for i in df.columns:
    if i not in ['LotFrontage', 'LotArea','1stFlrSF', '2ndFlrSF',  'Total Years']:
        pass
    else:
        cont_features.append(i)

In [58]:
cont_features

['LotFrontage', '1stFlrSF', '2ndFlrSF', 'Total Years']

In [57]:
## stacking cont variable to a tensor

cont_variable =  np.stack([df[i].values for i in cont_features],axis = 1)
cont_variable = torch.tensor(cont_variable,dtype=torch.float)
cont_variable

tensor([[  65.,  856.,  854.,   21.],
        [  80., 1262.,    0.,   48.],
        [  68.,  920.,  866.,   23.],
        ...,
        [  66., 1188., 1152.,   83.],
        [  68., 1078.,    0.,   74.],
        [  75., 1256.,    0.,   59.]])

In [60]:
cont_variable.dtype

torch.float32

In [62]:
y = torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)

In [63]:
y

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 9 columns):
MSSubClass     1460 non-null int64
MSZoning       1460 non-null int32
LotFrontage    1201 non-null float64
Street         1460 non-null int32
LotShape       1460 non-null int32
1stFlrSF       1460 non-null int64
2ndFlrSF       1460 non-null int64
SalePrice      1460 non-null int64
Total Years    1460 non-null int64
dtypes: float64(1), int32(3), int64(5)
memory usage: 85.6 KB


In [67]:
cat_feature.shape,cont_variable.shape,y.shape

(torch.Size([1460, 4]), torch.Size([1460, 4]), torch.Size([1460, 1]))

In [68]:
#####   EMBEDDING SIZE FOR CATEGORICAL VARIABLE

In [70]:
cat_dims = [len(df[cols].unique()) for cols in ['MSSubClass', 'MSZoning', 'Street', 'LotShape']]

In [71]:
cat_dims

[15, 5, 2, 4]

#### THUMPS RULE TO SET OUTPUT DIMENSION BASED ON INPUT DIM

##### input feature numbers + 1 and // 2     not more tthan 50

In [74]:
embedding_dim = [(x, min(50, (x+1)// 2)) for x in cat_dims]

In [75]:
embedding_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [77]:
import torch.nn as nn
import torch.nn.functional as F
embed_representation = nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
embed_representation

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [79]:
cat_feature

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [80]:
cat_feature = cat_feature[:4]

In [81]:
cat_feature

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])

In [82]:
pd.set_option('display.max_rows',500)
embedding_val=[]

In [83]:
for i,e in enumerate(embed_representation):
    embedding_val.append(e(cat_feature[:,i]))

In [84]:
embedding_val

[tensor([[-0.8649,  1.4442, -2.4038,  0.4607, -1.6097, -1.2316,  1.3595, -1.0647],
         [ 1.1668, -0.6127, -0.0366, -0.1552, -0.2130,  0.0284, -1.1829,  0.0234],
         [-0.8649,  1.4442, -2.4038,  0.4607, -1.6097, -1.2316,  1.3595, -1.0647],
         [-1.4354,  0.0685,  0.8425, -0.4071,  0.0134, -0.0360, -0.6042, -0.3931]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[ 0.9929, -1.7647, -0.2924],
         [ 0.9929, -1.7647, -0.2924],
         [ 0.9929, -1.7647, -0.2924],
         [ 0.9929, -1.7647, -0.2924]], grad_fn=<EmbeddingBackward0>),
 tensor([[0.2588],
         [0.2588],
         [0.2588],
         [0.2588]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.2082, -0.3739],
         [-0.2082, -0.3739],
         [ 0.8116, -0.5130],
         [ 0.8116, -0.5130]], grad_fn=<EmbeddingBackward0>)]

In [85]:
z = torch.cat(embedding_val,1)
z

tensor([[-0.8649,  1.4442, -2.4038,  0.4607, -1.6097, -1.2316,  1.3595, -1.0647,
          0.9929, -1.7647, -0.2924,  0.2588, -0.2082, -0.3739],
        [ 1.1668, -0.6127, -0.0366, -0.1552, -0.2130,  0.0284, -1.1829,  0.0234,
          0.9929, -1.7647, -0.2924,  0.2588, -0.2082, -0.3739],
        [-0.8649,  1.4442, -2.4038,  0.4607, -1.6097, -1.2316,  1.3595, -1.0647,
          0.9929, -1.7647, -0.2924,  0.2588,  0.8116, -0.5130],
        [-1.4354,  0.0685,  0.8425, -0.4071,  0.0134, -0.0360, -0.6042, -0.3931,
          0.9929, -1.7647, -0.2924,  0.2588,  0.8116, -0.5130]],
       grad_fn=<CatBackward0>)

In [86]:
dropout = nn.Dropout(.4)

In [87]:
final_embed = dropout(z)
final_embed

tensor([[-1.4415,  2.4070, -0.0000,  0.7678, -2.6828, -0.0000,  2.2658, -1.7745,
          0.0000, -2.9412, -0.0000,  0.0000, -0.3470, -0.0000],
        [ 1.9447, -1.0211, -0.0610, -0.2586, -0.0000,  0.0473, -1.9716,  0.0000,
          1.6548, -2.9412, -0.4873,  0.4313, -0.3470, -0.0000],
        [-1.4415,  0.0000, -0.0000,  0.0000, -2.6828, -0.0000,  0.0000, -0.0000,
          0.0000, -2.9412, -0.4873,  0.0000,  1.3526, -0.0000],
        [-2.3924,  0.1142,  1.4042, -0.6785,  0.0224, -0.0600, -1.0071, -0.0000,
          1.6548, -2.9412, -0.4873,  0.4313,  0.0000, -0.0000]],
       grad_fn=<MulBackward0>)