In [1]:
import numpy as np

In [3]:
Rev_arr = np.array([[180,200,220],[24,36,40], [12,18,20]])
Exp_arr = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [4]:
profit = Rev_arr - Exp_arr

In [5]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [10]:
# Total sales every year

price_per_unit = np.array([1000,200,200])

units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [11]:
np.dot(price_per_unit,units)

array([31400, 43000, 54400])

In [12]:
np.matmul(price_per_unit,units)

array([31400, 43000, 54400])

In [13]:
np.cross(price_per_unit,units)

array([[  2000, -44000,  34000],
       [  1000, -14000,   9000],
       [   400,  -6600,   4600]])

In [15]:
np.cross(units,price_per_unit)

array([[ -2000,  44000, -34000],
       [ -1000,  14000,  -9000],
       [  -400,   6600,  -4600]])